"""Static destination metadata. Keys are `normalize_key()` forms; values are ISO 3166-1 alpha-2."""

from __future__ import annotations

ALIASES: dict[str, str] = {
    "turkey": "TR",
    "ivory coast": "CI",
    "cote d ivoire": "CI",
    "usa": "US",
    "america": "US",
    "uk": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
    "russia": "RU",
    "north korea": "KP",
    "dprk": "KP",
    "czech republic": "CZ",
    "swaziland": "SZ",
    "burma": "MM",
    "macedonia": "MK",
    "east timor": "TL",
    "cape verde": "CV",
    "vatican": "VA",
    "vatican city": "VA",
    "holy see": "VA",
    "brunei": "BN",
    "palestine": "PS",
    "palestinian territories": "PS",
    "micronesia": "FM",
    "drc": "CD",
    "dr congo": "CD",
    "democratic republic of the congo": "CD",
    "democratic republic of congo": "CD",
    "congo kinshasa": "CD",
    "republic of the congo": "CG",
    "republic of congo": "CG",
    "congo brazzaville": "CG",
    "uae": "AE",
    "emirates": "AE",
    "hong kong sar": "HK",
    "macau": "MO",
    "macao sar": "MO",
    "kosovo": "XK",
    "falklands": "FK",
    "us virgin islands": "VI",
    "u s virgin islands": "VI",
    "british virgin islands": "VG",
    "sint maarten": "SX",
    "saint maarten": "SX",
    "bonaire": "BQ",
    "bonaire saint eustatius saba": "BQ",
    "pitcairn island": "PN",
    "holland": "NL",
    "turks and caicos": "TC",
    "saint kitts": "KN",
    "saint vincent": "VC",
    "antigua": "AG",
    "bosnia": "BA",
    "bosnia herzegovina": "BA",
    "sao tome": "ST",
}

AMBIGUOUS: dict[str, tuple[str, ...]] = {
    "congo": ("CG", "CD"),
    "korea": ("KR", "KP"),
    "virgin islands": ("VG", "VI"),
    "saint martin": ("MF", "SX"),
}

DISPLAY_NAME_OVERRIDES: dict[str, str] = {
    "RU": "Russia",
    "FM": "Micronesia",
    "PS": "Palestinian Territories",
    "VA": "Vatican City",
    "BN": "Brunei",
    "CD": "Democratic Republic of the Congo",
    "CG": "Republic of the Congo",
    "MF": "Saint Martin",
    "SX": "Sint Maarten",
    "VI": "U.S. Virgin Islands",
    "VG": "British Virgin Islands",
    "FK": "Falkland Islands",
}

# Codes used by all three governments that are not (yet) assigned in ISO 3166-1.
EXTRA_DESTINATIONS: dict[str, tuple[str, str | None]] = {
    "XK": ("Kosovo", "XKX"),
}
